# Generated by Django 4.0.1 on 2022-01-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('publication_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
