# Generated by Django 4.0.1 on 2022-01-10 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_alter_post_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=66, on_delete=django.db.models.deletion.PROTECT, related_name='my_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
